### ISSUE TITLE
What is the output of this code?

### ISSUE THREAD

**Issue by RayanAlshehhi** [RayanAlshehhi/SQA19F19112#3]
#include<iostream>
#include<vector>
using namespace std;
int main()
{ int n;
cout<<"Enter the number: ";
cin>>n;
vector<int> prime(n+1,1);
for(int i=2;i*i<=n;i++)
{ if(prime[i]==1)
{ for(int j=i;i*j<=n;j++)
{ prime[i*j]=0;
}
}
} cout<<"Prime number upto "<<n<<" are: ";
for(unsigned i=2;i<=prime.size();i++)
{ if(prime[i]==1)
{ cout<<i<<" ";
}
} cout<<endl;
return 0; }

**Comment by MaryamAlshehhi6** [comment]
Output
First Input:
Enter the number: 100
Prime number upto 100 are: 2 3 5 7 11 13 17 19 23 29 31 37 41 43
47 53 59 61 67 71 73 79 83 89 97
Second Input:
Enter the number: 200
Prime number upto 200 are: 2 3 5 7 11 13 17 19 23 29 31 37 41 43
47 53 59 61 67 71 73 79 83 89 97 101 103 107 109 113 127 131 137
139 149 151 157 163 167 173 179 181 191 193 197 199
